// Generates docs/SUPPORTED.md from the instruction and function registries, and
// docs/ERRORS.md from src/errors.ts.
import { readFileSync, writeFileSync } from 'node:fs';
import { build } from 'esbuild';

const bundle = await build({
  stdin: {
    contents: `export { instructions, UNSUPPORTED } from './src/xslt/compile';
      export { functions } from './src/xslt/runtime';
      export { coreFunctions } from './src/xpath/fn';`,
    resolveDir: '.',
    loader: 'ts',
  },
  bundle: true,
  format: 'esm',
  write: false,
  define: { __DEV__: 'true' },
  logLevel: 'error',
});
const mod = await import(
  `data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`
);

const list = (names) =>
  [...names]
    .sort()
    .map((n) => `\`${n}\``)
    .join(', ');
const core = [...mod.coreFunctions.keys()];
const xslt = [...mod.functions.keys()].filter((n) => !mod.coreFunctions.has(n));
const unsupported = mod.UNSUPPORTED.filter((n) => !mod.instructions.has(n));

writeFileSync(
  'docs/SUPPORTED.md',
  `# Supported features

Generated by \`pnpm docs:gen\` from the registries in the source; do not edit.

| Area | Supported |
|---|---|
| Top-level elements | \`xsl:stylesheet\`, \`xsl:transform\`, \`xsl:template\` (\`match\`, \`priority\`; named templates are accepted but cannot be called), \`xsl:variable\`, \`xsl:output\` (\`method\`, \`encoding\`) |
| Instructions | ${list(mod.instructions.keys())}, literal result elements with attribute value templates |
| XPath functions | ${list(core)} |
| XSLT functions | ${list(xslt)} |
| Output methods | \`html\`, \`xml\`, \`text\` |

Not supported, reported as error 2: ${list(unsupported.map((n) => `xsl:${n}`))}, the
\`mode\` attribute, attribute sets, the \`namespace\` axis, and the XSLT functions not listed
above. See [DIVERGENCES.md](DIVERGENCES.md) for differences in behavior.
`,
);

const src = readFileSync('src/errors.ts', 'utf8');
const codes = [...src.matchAll(/^\s+(\w+) = (\d+),$/gm)].map(([, name, n]) => [name, Number(n)]);
const messages = new Map(
  [...src.matchAll(/\[Code\.(\w+)\]: '([^']*)'/g)].map(([, name, m]) => [name, m]),
);
writeFileSync(
  'docs/ERRORS.md',
  `# Error codes

Generated by \`pnpm docs:gen\` from src/errors.ts; do not edit.

Errors are thrown as \`XSLTError\` with a numeric \`code\`. Production builds carry only the
code; development builds (\`dist/dev\`) also carry the message below and details.

| Code | Name | Meaning |
|---|---|---|
${codes.map(([name, n]) => `| ${n} | ${name} | ${messages.get(name) ?? ''} |`).join('\n')}
`,
);
console.log('docs/SUPPORTED.md and docs/ERRORS.md written');
